Fazer o cronograma do projeto
Requisitos-de-Software/2020.2-CarteiraDigitalTransito pull request #11
Opened 2021-02-15 10:58 UTC by estevaoreis25

## Descrição

Definição do cronograma das fases do projeto

## Issue Relacionada
[3](https://github.com/Requisitos-de-Software/2020.2-CarteiraDigitalTransito/issues/3)

2021-02-15 11:26 UTC, sergiosacj requested changes
Como essa é a primeira edição no documento, é interessante adicionar ao final do documento o campo de versionamento.

Sobre o cronograma, para ficar mais completo sugiro criar uma seção 2.2, detalhando a seção 2.1 (das fases). Nessa seção 2.2 seria detalhado o cronograma semanalmente, igual nesse [exemplo](https://ihc.sergiosacj.rocks/entrega_1/cronograma_atividades/).

Sugiro então que, nessa seção 2.2, o cronograma seja completo e feito baseado no cronograma fornecido pelo professor, apresentado no plano de ensino da disciplina.

E, se possível, adicionar todas as alterações nesse PR (cronograma + introdução). Assim a gente evita problemas de merge desnecessários. Para fazer isso basta editar esse PR com as informações da introdução e editar o commit inicial, que está apagando e adicionando a introdução ao mesmo tempo.

Se precisar de ajuda para realizar essas alterações é só avisar :)

2021-02-15 11:45 UTC, estevaoreis25 commented
> Como essa é a primeira edição no documento, é interessante adicionar ao final do documento o campo de versionamento.
> 
> Sobre o cronograma, para ficar mais completo sugiro criar uma seção 2.2, detalhando a seção 2.1 (das fases). Nessa seção 2.2 seria detalhado o cronograma semanalmente, igual nesse [exemplo](https://ihc.sergiosacj.rocks/entrega_1/cronograma_atividades/).
> 
> Sugiro então que, nessa seção 2.2, o cronograma seja completo e feito baseado no cronograma fornecido pelo professor, apresentado no plano de ensino da disciplina.
> 
> E, se possível, adicionar todas as alterações nesse PR (cronograma + introdução). Assim a gente evita problemas de merge desnecessários. Para fazer isso basta editar esse PR com as informações da introdução e editar o commit inicial, que está apagando e adicionando a introdução ao mesmo tempo.
> 
> Se precisar de ajuda para realizar essas alterações é só avisar :)

Sobre o detalhamento das atividades, em vez de haver uma sessão 2.2, pensei em fazer como no exemplo que deu e colocar o detalhamento dentro da propria tabela do cronograma. O que acha?

2021-02-15 11:50 UTC, sergiosacj commented
> > Como essa é a primeira edição no documento, é interessante adicionar ao final do documento o campo de versionamento.
> > Sobre o cronograma, para ficar mais completo sugiro criar uma seção 2.2, detalhando a seção 2.1 (das fases). Nessa seção 2.2 seria detalhado o cronograma semanalmente, igual nesse [exemplo](https://ihc.sergiosacj.rocks/entrega_1/cronograma_atividades/).
> > Sugiro então que, nessa seção 2.2, o cronograma seja completo e feito baseado no cronograma fornecido pelo professor, apresentado no plano de ensino da disciplina.
> > E, se possível, adicionar todas as alterações nesse PR (cronograma + introdução). Assim a gente evita problemas de merge desnecessários. Para fazer isso basta editar esse PR com as informações da introdução e editar o commit inicial, que está apagando e adicionando a introdução ao mesmo tempo.
> > Se precisar de ajuda para realizar essas alterações é só avisar :)
> 
> Sobre o detalhamento das atividades, em vez de haver uma sessão 2.2, pensei em fazer como no exemplo que deu e colocar o detalhamento dentro da propria tabela do cronograma. O que acha?

Acho Bacana, sugeri criar uma nova seção apenas para oferecer mais opções. Caso o interesse fosse no cronograma resumido bastaria olhar a seção 2.1, caso contrário teria a seção 2.2 detalhando. Nesse ponto fica à seu critério.

2021-02-16 12:45 UTC, sergiosacj approved these changes
Tudo certo agora :)

2021-02-16 12:45 UTC, merged