Cenários
Requisitos-de-Software/2020.2-CarteiraDigitalTransito pull request #46
Opened 2021-03-21 00:24 UTC by DanielPortods

## Descrição
Realização da atividade relacionada a técnica de cenários.

## Tarefas Realizadas
- Traçados os cenários das funcionalidades do CDT

## Issues Relacionadas
Closes #42

2021-03-21 00:50 UTC, emysdias requested changes

2021-03-21 00:50 UTC, emysdias commented on docs/modelagem/cenarios.md
> +&emsp;&emsp;A aplicação da técnica deu-se com auxílio dos participantes da equipe que utilizam a aplicação. É interessante mostrar que, por ter u escopo razoavelmente grande, o CDT tem uma maga muito
```suggestion
&emsp;&emsp;A aplicação da técnica deu-se com auxílio dos participantes da equipe que utilizam a aplicação. É interessante mostrar que, por ter um escopo razoavelmente grande, o CDT tem uma maga muito ramificada de usuários por funcionalidades. Por exemplo, nem sempre um usuário tem veículos em seu nome e, se ele fosse utilizado para traçar os cenários, as funcionalidades referentes a veículos ficariam de fora da técnica.<br>
```

2021-03-21 00:50 UTC, emysdias commented on docs/modelagem/cenarios.md
> +| **Objetivo** | Acessar o Histótico de habilitações.  |
```suggestion
| **Objetivo** | Acessar o Histórico de habilitações.  |
```

2021-03-21 00:50 UTC, emysdias commented on docs/modelagem/cenarios.md
> +| **Objetivo** | Declarar o real responsável por uma infrção. |
```suggestion
| **Objetivo** | Declarar o real responsável por uma infração. |
```

2021-03-21 00:50 UTC, emysdias commented on docs/modelagem/cenarios.md
> +| **Episódios** | - Usuário toca no íconde de câmera a baixo do cículo onde está a inicial do seu nome. |
```suggestion
| **Episódios** | - Usuário toca no ícone de câmera a baixo do círculo onde está a inicial do seu nome. |
```

2021-03-21 02:22 UTC, enzoggqs commented on docs/modelagem/cenarios.md
> +&emsp;&emsp;A aplicação da técnica deu-se com auxílio dos participantes da equipe que utilizam a aplicação. É interessante mostrar que, por ter u escopo razoavelmente grande, o CDT tem uma maga muito
```suggestion
&emsp;&emsp;A aplicação da técnica deu-se com auxílio dos participantes da equipe que utilizam a aplicação. É interessante mostrar que, por ter u escopo razoavelmente grande, o CDT tem uma gama muito ramificada de usuários por funcionalidades. Por exemplo, nem sempre um usuário tem veículos em seu nome e, se ele fosse utilizado para traçar os cenários, as funcionalidades referentes a veículos ficariam de fora da técnica.<br>
```

2021-03-21 02:23 UTC, enzoggqs commented on docs/modelagem/cenarios.md
> +&emsp;&emsp;Para especificar os cénarios será foram utilizadas tabelas contendo os seguintes Elementos:
```suggestion
&emsp;&emsp;Para especificar os cénarios foram utilizadas tabelas contendo os seguintes Elementos:
```

2021-03-22 00:48 UTC, emysdias approved these changes
🏆 arrasou

2021-03-22 01:06 UTC, enzoggqs approved these changes
Show!

2021-03-22 01:06 UTC, merged