43 casos de uso
Requisitos-de-Software/2020.2-CarteiraDigitalTransito pull request #47
Opened 2021-03-21 05:13 UTC by emysdias

## Descrição

## Tarefas Realizadas
- [x] Foi feito o diagrama de casos de uso e o documento

## Issues Relacionadas
#43

2021-03-21 12:25 UTC, sergiosacj requested changes
Ficou faltando só a metodologia mesmo. No mais, tudo ótimo!

2021-03-21 16:19 UTC, emysdias commented
> Ficou faltando só a metodologia mesmo. No mais, tudo ótimo!

a metodologia ficou na introdução do documento

2021-03-21 16:50 UTC, sergiosacj commented
> > Ficou faltando só a metodologia mesmo. No mais, tudo ótimo!
> 
> a metodologia ficou na introdução do documento

Então, eu acho que da para criar a sessão de metodologia à parte, apenas descrevendo os campos da tabela. Na introdução eu acho que ficaria legal chamar caso de uso de técnica e não de metodologia.

2021-03-21 17:44 UTC, DanielPortods commented on docs/modelagem/caso_de_uso.md
> +| :---------------: | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Não entendi pq tá assim... 😅

2021-03-22 00:43 UTC, emysdias commented on docs/modelagem/caso_de_uso.md
> +| :---------------: | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
é a formatação do prettier

2021-03-22 00:43 UTC, emysdias commented on docs/modelagem/caso_de_uso.md
> +| :---------------: | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
mas o documento fica normal

2021-03-22 01:35 UTC, DanielPortods approved these changes
Pois bem. Como esse artefato deve estar publicado para a segunda entrega, acredito que o melhor agora é publicar essa versão e colocar a questão levantada sobre a metodologia no conjunto de ajustes a serem feitos até a entrega final do projeto.
@sergiosacj  o que acha?

2021-03-22 16:07 UTC, sergiosacj commented
> Pois bem. Como esse artefato deve estar publicado para a segunda entrega, acredito que o melhor agora é publicar essa versão e colocar a questão levantada sobre a metodologia no conjunto de ajustes a serem feitos até a entrega final do projeto.
> @sergiosacj o que acha?

Justo, vou realizar o merge

2021-03-22 16:07 UTC, merged

2021-03-22 16:08 UTC, sergiosacj commented
Vou manter sem aprovação, desse modo conseguimos lembrar o que ficou faltando.