Documento moscow verificação
Requisitos-de-Software/2020.2-CarteiraDigitalTransito pull request #71
Opened 2021-04-10 23:47 UTC by emysdias

## Descrição

## Tarefas Realizadas
- [ ] foi feito o documento de verificação do moscow

## Issues Relacionadas
#70

2021-04-13 15:27 UTC, DanielPortods reviewed
Só tá faltando isso.

2021-04-13 15:27 UTC, DanielPortods commented on docs/analise/verificacao/moscow.md
> +- Inspetor: Daniel Porto.
O padrão que estamos usando é o sgeuinte:

- Técnica: qual técnica está sendo utilizada na verificação
 - Autores: os autores do documento que está sendo verificado
 - Revisores: o par que revisou o documento que está sendo verificado
 - Inspetores: quem está realizando a verificação

2021-04-13 15:27 UTC, DanielPortods commented on docs/analise/verificacao/moscow.md
> +
Existe uma pendência na issue #53 sobre essa artefato que poderia ter sido abordada nessa verificação.

2021-04-15 00:25 UTC, DanielPortods requested changes
Ajustes finais.

2021-04-15 00:25 UTC, DanielPortods commented on mkdocs.yml
>          - Protótipo: analise/validacao/prototipo.md
Vai dar um conlfito por aqui por conta de outros prs. Além disso, como não será feita a validação informal, pode retirar da nav.

2021-04-15 10:43 UTC, emysdias commented on mkdocs.yml
>          - Protótipo: analise/validacao/prototipo.md
e como q vai ficar visível pra ver o documento? é só eu arrumar o conflito

2021-04-15 15:04 UTC, DanielPortods approved these changes
🎉

2021-04-15 15:05 UTC, merged