66 verificacao backlog
Requisitos-de-Software/2020.2-CarteiraDigitalTransito pull request #75
Opened 2021-04-11 13:41 UTC by estevaoreis25

## Descrição
Verificação do Backlog 

## Issues Relacionadas
[#66](https://github.com/Requisitos-de-Software/2020.2-CarteiraDigitalTransito/issues/66)

2021-04-13 15:26 UTC, DanielPortods requested changes
Acho que só falta isso, dê uma olhada nos outros PRs de verificação pra checar o padrão para linkar o doc.

2021-04-13 15:26 UTC, DanielPortods commented on docs/analise/verificacao/backlog.md
> + - Inspetores: Estevão Reis
Falta o link para o documento que está sendo verificado.

2021-04-13 15:26 UTC, DanielPortods commented on docs/analise/verificacao/historia_de_usuario.md
> +
Falta o link para o documento que está sendo verificado.

2021-04-14 11:18 UTC, estevaoreis25 commented
Correções feitas

2021-04-15 00:13 UTC, DanielPortods approved these changes
🏆

2021-04-15 00:14 UTC, merged