(#74) Criando o documento
Requisitos-de-Software/2020.2-CarteiraDigitalTransito pull request #80
Opened 2021-04-13 15:24 UTC by yandrade1305

## Descrição
Fazer o documento de verificação dos léxicos
## Tarefas Realizadas
Realizar verificação
Fazer checklist
Fazer correções caso seja necessário

## Issues Relacionadas
(#74)

2021-04-14 00:01 UTC, emysdias requested changes

2021-04-14 00:01 UTC, emysdias commented on docs/analise/verificacao/lexico.md
> +| 1.0 | 13/04/2021 | Criação do documento | Yan |
Acho melhor colocar q adicionou os tópicos ao documento do q criação, mas fica a seu critério

2021-04-15 00:51 UTC, DanielPortods commented
Falta:
- Labels;
- Assignee;
- milestone;

2021-04-15 11:23 UTC, yandrade1305 commented on docs/analise/verificacao/lexico.md
> +| 9	| Possui noção correta?|
Noção = Denotação
É um dos tópicos que definem o que é um léxico

2021-04-15 16:07 UTC, emysdias approved these changes
🏆 brabor

2021-04-15 16:07 UTC, merged