(#77) Criando o documento
Requisitos-de-Software/2020.2-CarteiraDigitalTransito pull request #81
Opened 2021-04-13 15:27 UTC by yandrade1305

## Descrição

## Tarefas Realizadas
Fazer a verificação do First Things First

## Issues Relacionadas
(#77)

2021-04-14 11:33 UTC, estevaoreis25 commented on docs/analise/verificacao/first_things_first.md
> +## Contexto
Inserir numeração de cada tópico e subtópico: Exemplo: 1. Contexto, 2.Checklist, 2.1 Critérios ....

2021-04-14 11:38 UTC, estevaoreis25 commented on docs/analise/verificacao/first_things_first.md
> +- Técnica utilizada: Técnica de Leitura Check-List
Está faltando a informação de Revisores do documento. 
O contexto deve conter essas informações:
 - Técnica 
 - Autores 
 - Revisores
 - Inspetores
 - Link pro documento

2021-04-14 11:42 UTC, estevaoreis25 commented on docs/analise/verificacao/first_things_first.md
> +- Inspetor: Estevão Reis.
Informações de Autor do documento e inspetor estao incorretas:
- Autores: Criadores do documento verificado, ou seja, no caso, os criadores do documento "First Things First"
- Inspetor: Quem verificou o documento, no caso, você
- Revisores: Quem revisou o documento verificado, no caso , os revisores do documento "First Things First"

2021-04-14 11:44 UTC, estevaoreis25 commented on docs/analise/verificacao/first_things_first.md
> +
Como uma sugestão válida, acredito que poderia ter um tópico de "Conclusão" onde é dito que todo o documento foi verificado e que não foi encontrados erros referentes ao que está estabelecidos no checklist

2021-04-14 11:46 UTC, estevaoreis25 requested changes
Acredito que fazendo essas correções, o documento fica completo

2021-04-15 00:37 UTC, DanielPortods requested changes
O item 3.1 não é preciso quando se tem poucos tópicos. As perguntas vão direto nos resultados.
Quando mudar, se lembre de corrigir a numeração dos subtópicos.

2021-04-15 00:37 UTC, DanielPortods commented on docs/analise/verificacao/first_things_first.md
> +
Como discutido anteriormente, o padrão para documentos que têm poucos tópicos a serem verificados deve ser com as perguntas já na parte dos resultados com as respostas do lado.
Na forma:
|Número|Pergunta|Resposta| 
|:-:|--|--|

2021-04-15 00:39 UTC, DanielPortods commented
Atualize com a main para resolver os conflitos

2021-04-15 00:41 UTC, DanielPortods commented
Falta: 
- Labels;
- Milestone.

O pr tá com nome de commit também. Se atentar nesses detalhes.

2021-04-15 12:18 UTC, estevaoreis25 commented
A atribuição de Autor e Inspetor continua errada. O Autor é quem criou o documento First Things First, o Inspetor é voce que verificou o documento

2021-04-15 15:07 UTC, DanielPortods approved these changes

2021-04-16 20:05 UTC, merged