Revisão de arquivos
Requisitos-de-Software/2020.2-CarteiraDigitalTransito pull request #88
Opened 2021-04-24 20:53 UTC by emysdias

## Descrição

## Tarefas Realizadas
- Foi arrumado o documento de FTF, NFR  e rich picture

## Issues Relacionadas
#87

2021-04-27 03:14 UTC, DanielPortods requested changes
Acho que é só isso.

2021-04-27 03:14 UTC, DanielPortods commented on docs/priorizacao/first_thing_first.md
> +
Material do materiais, redundância?

2021-04-27 03:14 UTC, DanielPortods commented on docs/priorizacao/first_thing_first.md
Faltou o versionamento.

2021-04-27 03:14 UTC, DanielPortods commented on docs/analise/verificacao/moscow.md
A conclusão deve ser adaptada, já que foram retirados os pontos dos léxicos da verificação.

2021-04-27 03:22 UTC, DanielPortods commented
Na verificação do NFR foram levantadas algumas questões, acha que daria pra corrigir o que foi levnatado?

2021-04-27 03:23 UTC, DanielPortods commented
Falta também o acompanhamento no documento de verificação do MoSCoW, já que foram corrigidos os pontos levantados na verificação.

2021-05-02 01:04 UTC, enzoggqs approved these changes

2021-05-02 15:07 UTC, DanielPortods approved these changes

2021-05-02 15:08 UTC, merged