Revisão dos arquivos Introspeção e Histórias de Usuário
Requisitos-de-Software/2020.2-CarteiraDigitalTransito pull request #95
Opened 2021-04-30 17:50 UTC by estevaoreis25

## Descrição
Ajustes nos artefatos de Introspeção e Histórias de Usuário

## Tarefas Realizadas
### Introspecção:
 Realocação da introdução;
 Descrição da metodologia;

### História de usuários:

 Historias de Usuário inseridas em uma tabela para facilitar a leitura
 Todos os erros apontados na verificação corrigos

## Issues Relacionadas
[#86]

2021-05-01 19:28 UTC, emysdias requested changes
Acho q arrumando esses ta tranquilo 🏆

2021-05-01 19:28 UTC, emysdias commented on docs/elicitacao/introspeccao.md
>  A introspecção é o primeiro e mais óbvio métodos para tentar entender quais propriedades um sistema deve ter para ter sucesso.
```suggestion
A introspecção é o primeiro método e o mais intuitivo para tentar entender quais propriedades um sistema deve ter para ter sucesso.
```

2021-05-01 19:28 UTC, emysdias commented on docs/modelagem/historia_de_usuario.md
> +&emsp;&emsp; "Uma história de usuário é uma breve declaração que descreve algo que o sistema deve fazer para o usuário. É um tipo de especificação de requisitos adotado por muitas equipes de projetos
```suggestion
&emsp;&emsp; "Uma história de usuário é uma breve declaração que descreve algo que o sistema deve fazer para o usuário. É um tipo de especificação de requisitos adotado por muitas equipes de projetos 'ágeis'. Ela se restringe a definir o escopo sem entrar no detalhamento do passo a passo ou das regras de negócio que se aplicam à tarefa do software. Os detalhes do comportamento do sistema são desenvolvidos por meio de interações entre a equipe de desenvolvimento e o dono do produto; pela definição de um critério de aceitação." (VAZQUEZ, Carlos Eduardo, SIMÕES, Guilherme Siqueira. Engenharia de Requisitos: Software Orientado ao Negócio).
```

2021-05-02 14:50 UTC, estevaoreis25 commented on docs/modelagem/historia_de_usuario.md
> +&emsp;&emsp; "Uma história de usuário é uma breve declaração que descreve algo que o sistema deve fazer para o usuário. É um tipo de especificação de requisitos adotado por muitas equipes de projetos
Tudo corrigido

2021-05-02 14:55 UTC, emysdias approved these changes
🏆 boa

2021-05-02 15:28 UTC, sergiosacj approved these changes

2021-05-02 15:28 UTC, merged

2021-05-02 15:31 UTC, DanielPortods approved these changes